services:
  redis-broker:
    image: redis:7 
    container_name: job_master_redis_broker 
    ports:
      - "6379:6379" 
    command: redis-server --appendonly yes 
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf 
      - redis_data:/data 

  db: # The database service
    image: postgres # Using the oficial dockerhub image
    container_name: postgres
    networks:
      - api-network # Connect to the network to be used by other containers (ej: the web server)
    environment: # all the enviroment variables defined in the container (see postgres official image docs https://hub.docker.com/_/postgres)
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: stocks_db
    
    volumes:
      # To persist the data in the database we have a volume that persist after container deletion
      # and copy the files from the container to the volume.
      - db-volume:/var/lib/postgresql/data 

  jobmaster:
    build:
      context: ./project
      dockerfile: Dockerfile
    container_name: job_master_api
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./project:/app
    depends_on:
      - redis-broker
      - db 
    environment:
      PYTHONUNBUFFERED: 1
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      REDIS_HOST: redis-broker
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    networks: # Añade la red también para este servicio
      - api-network

  worker:
    build:
      context: ./project
      dockerfile: Dockerfile
    container_name: job_master_celery_worker_1
    command: celery -A consumer.celery_app worker --loglevel=info
    volumes:
      - ./project:/app
    depends_on:
      - redis-broker
      - db 
    environment:
      PYTHONUNBUFFERED: 1
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db 
      DB_PORT: ${DB_PORT}
      REDIS_HOST: redis-broker 
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    networks:
      - api-network

  celery_beat:
    build:
      context: ./project
      dockerfile: Dockerfile
    container_name: job_master_celery_beat
    command: celery -A consumer.celery_app beat --loglevel=info
    volumes:
      - ./project:/app
    depends_on:
      - redis-broker
      - db 
    environment:
      PYTHONUNBUFFERED: 1
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      REDIS_HOST: redis-broker 
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    networks: 
      - api-network


networks:
  api-network:


volumes:
  redis_data:
  db-volume: 